### ISSUE TITLE
这种情况是bug中提到的问题吗？

### ISSUE THREAD

**Issue by yaxiang962** [lisonge/pixiv-popular-sort#1]
刷新了几次还是没有排序返回，查看控制台有这些信息，是服务器端出问题还是我没设置好？
![360截图20210521215746674](https://user-images.githubusercontent.com/84578907/119149864-7cf5dd00-ba80-11eb-8752-9df750159537.jpg)

**Comment by lisonge** [comment]
是服务端的问题，我刚开始发现的时候概率还比较小，但是现在概率很大，我也不知道为什么。

猜测是用的人太多了，pixiv 官方 做了特殊处理。

那个日志输出的是一个列表`arr`，arr[0] 是否该请求被拦截，arr[1] 是 拦截的 url

还有就是我忘记把日志输出关闭了，控制台一堆输出，下个版本会关闭输出

**Comment by yaxiang962** [comment]
谢谢回答！
隔壁pixiv_sort_by_popularity by zhuzemin的脚本，点击Sort by popularity后一直在searching，试了好几次也不行，感觉pixiv又搞幺蛾子了。
难得的好脚本，希望都能恢复使用吧。
