### ISSUE TITLE
失效了吗？

### ISSUE THREAD

**Issue by SsuJojo** [lisonge/pixiv-popular-sort#2]
已失效？

**Comment by lisonge** [comment]
是的，这个的前提是有人提供 会员 token 或者 会员代理 的 api 接口

**Comment by lisonge** [comment]
一个不需要会员的方案

你可以在客户端批量请求然后自己排序输出

比如我之前写过一个方案，批量查询分页接口，筛选收藏大于300的作品，查询前 1000 个数据然后排序输出

中途查询太快会触发接口限制，可以使用某些分流工具，将流量使用不同的代理节点传输可以解决这个问题
